### PR TITLE
add netapp

### PR DESCRIPTION
**Pull request by zhixiangteoh**

### CODE REVIEW

**Comment by zejunliu** [comment]
Snap rejected me immediately after I submitted my application? Is it just me ):

**Comment by varughese** [comment]
happens to the best of us bro @zejunliu

**Comment by aidev1065** [comment]
What did the email say?

**Comment by zejunliu** [comment]
They sent me two emails at the same time :
The fist one says:

Thanks so much for your interest in Snap Inc. We really appreciate the time you invested in the application process.

Although we saw a lot of strengths in your background we feel there isn’t the perfect match at this time and we have decided not to proceed with your candidacy for the following role. 

Software Engineer Intern 2021 (Application Window #1: Aug 17th - Sep 4th) 

We hope you keep us in mind as we continue to grow and as our needs change. We wish you both personal and professional success in your job search.

Thanks,

The second one says:

Thank you for applying to the Software Engineer Intern 2021 (Application Window #1: Aug 17th - Sep 4th) role. Your profile will be reviewed against current openings and closely related positions. We appreciate your effort so far, and if there is a good fit to our needs, we will contact you. 

And I check the status on the workday, it says ‘rejected’.

**Comment by swechha16** [comment]
I got that exact email too! Legit 2 mins after I applied

**Comment by aidev1065** [comment]
Dang hopefully it's a bug on their end. Seems like you all are hardworking and super talented. Don't let it bring you down 😁

**Comment by zejunliu** [comment]
Haha, the same thing happened to me a few days ago when I applied for Disney internship .

**Comment by ayoung19** [comment]
Same thing happened to me, rejection email was literally 10s after the confirmation.

**Pull request merged**
