### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by florayym**
I propose that when a link is broken after the company closes that application portal, the item remains but add a closed notice in its Notes field.

### CODE REVIEW

**Comment by Zmwang622** [comment]
Any reasoning?

**Comment by florayym** [comment]
Because this will synchronously delete the line from the google form that used to track the status of the intern application.

**Comment by CDuke-Janus** [comment]
To flex on everyone who didn't apply in time, obviously /s
No but actually this is a good idea to keep people from being confused when they see others talking about applying to certain roles online but not actually being able to find them on the list.

**Comment by jasonlaw-dev** [comment]
Agreed. Another point is students aiming for Summer 2022 internships can refer to the current list for a list of companies who offer internships, but don't have to go through the commit histories for deleted entries

Adding notes or a strikethrough would be a great idea.

**Comment by CookieComputing** [comment]
+1, like @jasonlaw-dev said, it'd be great to have a list for the next season!

**Comment by Zmwang622** [comment]
So will putting closed in the description be sufficient and removing the link be sufficient because I'm down

**Pull request merged**
