### PR TITLE
Added 10 internships.

### PR DESCRIPTION
**Pull request by GintasS**
Added internships. Should I continue doing this, do I help anybody by doing this?

### CODE REVIEW

**Comment by Camless** [comment]
I check every day. I appreciate the time and detail you put into this.

**Comment by GintasS** [comment]
> I check every day. I appreciate the time and detail you put into this.

Thank you :)

**Comment by anishagg17** [comment]
Is there any opening for Indians?

**Comment by GintasS** [comment]
> Is there any opening for Indians?

I think most of the positions are opened to all the ethnicities.

**Pull request merged**
